# Generated by Django 2.2.8 on 2020-07-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This Is a Test Description sfsdfsfsfsfsdfsdf kjjkjljlkjlkjlkjkl ffs'),
            preserve_default=False,
        ),
    ]
